name: NASA Project CI
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build:
    env:
      # Used to disable watch mode on test scripts
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: npm run build --prefix client
      - run: npm test
